2018-10-17 22:08:39,325 ERROR: Exception on /specificquoteresult/AAPl [GET] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 41, in specificquoteresult
    return render_template("specificquoteresult.html", title='Quote Result', quote_result=quote_result, ticker_symbol=ticker_symbol)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/gene/.local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/gene/.local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/gene/.local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/gene/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: specificquoteresult.html
2018-10-17 22:11:19,159 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-17 22:11:30,540 ERROR: Exception on /pricequoteresult/MTSAIOTSA [GET] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 40, in pricequoteresult
    quote_result=quote(ticker_symbol)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 251, in quote
    return json.loads(response)['LastPrice']
KeyError: 'LastPrice'
2018-10-17 22:12:11,974 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-17 22:12:14,843 ERROR: Exception on /pricequoteresult/bac [GET] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 41, in pricequoteresult
    return render_template("pricequoteresult.html", title='Quote Result', quote_result=float(quote_result, 2), ticker_symbol=ticker_symbol)
TypeError: float() takes at most 1 argument (2 given)
2018-10-17 22:12:19,237 ERROR: Exception on /pricequoteresult/BAC [GET] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 41, in pricequoteresult
    return render_template("pricequoteresult.html", title='Quote Result', quote_result=float(quote_result, 2), ticker_symbol=ticker_symbol)
TypeError: float() takes at most 1 argument (2 given)
2018-10-17 22:12:50,553 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-17 22:13:09,234 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-17 22:13:21,738 ERROR: Exception on /buy [POST] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 74, in buy
    user_buy = buy_stock(current_user=current_user, ticker_symbol=form.ticker_symbol.data, number_of_shares=form.number_of_shares.data)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 213, in buy_stock
    holding = get_holding(current_user, ticker_symbol)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 168, in get_holding
    if holding[0].ticker_symbol == None:
IndexError: list index out of range
2018-10-17 22:13:28,648 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-17 22:14:14,530 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
